apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-info-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-info-app
  template:
    metadata:
      labels:
        app: k8s-info-app
    spec:
      containers:
        - name: k8s-info-app
          image: olegan/k8s-info-app:0.0.1
          ports:
          - containerPort: 5000
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "100m"
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: APP_VERSION
              value: "0.0.1"
            - name: APP_TITLE
              value: "Base app"
            - name: APP_DESCRIPTION
              value: "Base app"
