apiVersion: v1
kind: Service
metadata:
  name: k8s-info-app
spec:
  selector:
    app: k8s-info-app
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 30008
  type: NodePort
