apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monorepo-app-2
  namespace: default
spec:
  interval: 10m
  path: "./apps-infra/monorepo-app-2/deploy"
  prune: true
  sourceRef:
    kind: GitRepository
    name:  monorepo-app-2