apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: monorepo-app-1
  labels:
    app: monorepo-app-1
spec:
  type: NodePort
  selector:
    app: monorepo-app-1
  ports:
    - protocol: TCP
      name: http
      port: 5000
      targetPort: 5000
      nodePort: 30001