---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: helm-repo-app
  namespace: default
spec:
  chart:
    spec:
      chart: helm-repo-app
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: helm-repo-app
  interval: 1m0s
  releaseName: helm-repo-app
  targetNamespace: default
