apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: monorepo-app-1
  namespace: default
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/OLG-MAN/gitops_demo.git