---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: helm-git-app
  namespace: default
spec:
  interval: 1m0s
  ref:
    branch: helm-git-app
  url: https://github.com/OLG-MAN/gitops_demo_app
