apiVersion: apps/v1
kind: Deployment
metadata:
  name: monorepo-app-2
  labels:
    app: monorepo-app-2
  namespace: default
spec:
  selector:
    matchLabels:
      app: monorepo-app-2
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: monorepo-app-2
    spec:
      containers:
      - name: monorepo-app-2
        image: olegan/monorepo-app-2:0.0.1 # {"$imagepolicy": "default:monorepo-app-2"}
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: config-volume
          mountPath: /configs/
      volumes:
      - name: config-volume
        configMap:
          name: monorepo-app-2
