name: Build and Push monorepo-app-2

on:
  push:
    paths:
      - 'apps/monorepo-app-2/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: demo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Check commit message for 'build' keyword
        id: check_commit_message
        run: |
          echo "Checking commit message..."
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "Commit message: $COMMIT_MESSAGE"
          if [[ "$COMMIT_MESSAGE" == *"build"* ]]; then
            echo "::set-output name=should_build::true"
          else
            echo "::set-output name=should_build::false"
          fi

      - name: Log in to Docker Hub
        if: steps.check_commit_message.outputs.should_build == 'true'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        if: steps.check_commit_message.outputs.should_build == 'true'
        uses: docker/build-push-action@v2
        with:
          context: ./apps/monorepo-app-2/src
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/monorepo-app-1:latest

      - name: Log out from Docker Hub
        if: steps.check_commit_message.outputs.should_build == 'true'
        run: docker logout